export const ATM_STATE_START = 'ATM_START';
export const ATM_STATE_WITHDRAW = 'ATM_STATE_WITHDRAW';
export const ATM_STATE_DEPOSIT = 'ATM_STATE_DEPOSIT';
export const ATM_STATE_ERROR = 'ATM_STATE_ERROR';